apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinkeeper-backend
  namespace: coinkeeper
  labels:
    app: coinkeeper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinkeeper-backend
  template:
    metadata:
      labels:
        app: coinkeeper-backend
    spec:
      containers:
        - name: backend
          image: coinkeeper-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: coinkeeper-backend
  namespace: coinkeeper
  labels:
    app: coinkeeper-backend
spec:
  selector:
    app: coinkeeper-backend
  ports:
    - name: http
      port: 5001        # service port inside cluster
      targetPort: 5001  # containerPort
  type: ClusterIP
