apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgets-service
  namespace: coinkeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budgets-service
  template:
    metadata:
      labels:
        app: budgets-service
    spec:
      containers:
        - name: budgets-service
          image: coinkeeper-budgets-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
          envFrom:
            - secretRef:
                name: coinkeeper-backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: budgets-service
  namespace: coinkeeper
spec:
  selector:
    app: budgets-service
  ports:
    - port: 5004
      targetPort: 5004
      protocol: TCP
  type: ClusterIP
