apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
  namespace: coinkeeper
  labels:
    app: expense-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense-service
          image: coinkeeper-expense:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb://coinkeeper:supersecretpassword@mongo:27017/coinkeeper?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: coinkeeper
  labels:
    app: expense-service
spec:
  selector:
    app: expense-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003
  type: ClusterIP
