apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-service
  namespace: coinkeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expenses-service
  template:
    metadata:
      labels:
        app: expenses-service
    spec:
      containers:
        - name: expenses-service
          image: coinkeeper-expenses-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
          envFrom:
            - secretRef:
                name: coinkeeper-backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: expenses-service
  namespace: coinkeeper
spec:
  selector:
    app: expenses-service
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
  type: ClusterIP
