apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinkeeper-frontend
  namespace: coinkeeper
  labels:
    app: coinkeeper-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinkeeper-frontend
  template:
    metadata:
      labels:
        app: coinkeeper-frontend
    spec:
      containers:
        - name: frontend
          image: coinkeeper-frontend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: coinkeeper-frontend
  namespace: coinkeeper
  labels:
    app: coinkeeper-frontend
spec:
  selector:
    app: coinkeeper-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
