apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coinkeeper-ingress
  namespace: coinkeeper
spec:
  ingressClassName: nginx
  rules:
    - host: coinkeeper.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5002
          - path: /api/expenses
            pathType: Prefix
            backend:
              service:
                name: expenses-service
                port:
                  number: 5003
          - path: /api/budgets
            pathType: Prefix
            backend:
              service:
                name: budgets-service
                port:
                  number: 5004
          - path: /api/analytics
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 5005
