apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coinkeeper-ingress
  namespace: coinkeeper
spec:
  ingressClassName: nginx
  rules:
    - host: coinkeeper.local
      http:
        paths:
          # Frontend React app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: coinkeeper-frontend
                port:
                  number: 80

          # Auth service
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5002

          # Expenses + budgets
          - path: /api/expenses
            pathType: Prefix
            backend:
              service:
                name: expense-service
                port:
                  number: 5003
          - path: /api/budgets
            pathType: Prefix
            backend:
              service:
                name: expense-service
                port:
                  number: 5003

          # Analytics
          - path: /api/analytics
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 5004
